version: '3.8'

services:
  # Django application service
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "  # Command to run when the container starts
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment: 
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=ecosync_project.settings
      - PYTHONPATH=/app
